### ISSUE TITLE
Video on WinLamb

### ISSUE THREAD

**Issue by LegalizeAdulthood** [rodrigocfd/winlamb#15]
Hi,

I recently gave a detailed presentation on WinLamb for Utah C++ Programmers.

You can find the video here: https://www.youtube.com/watch?v=2K52YX-vHv4

Feel free to link it from your documentation if you like.

**Comment by rodrigocfd** [comment]
Hi Richard,

Great talk, very insightful and entertaining. Yes, it's a great resource and I'll link it.

Thanks for sharing.
