### ISSUE TITLE
base_window.h error C2664

### ISSUE THREAD

**Issue by BeErikk** [rodrigocfd/winlamb#2]
Hi Rodrigo

I get:
`base_window.h(129): error C2664: 'LONG_PTR std::_Func_class<_Ret,wl::params &>::operator ()(wl::params &) const': cannot convert argument 1 from 'wl::params' to 'wl::params &'
...note: A non-const reference may only be bound to an lvalue`
code:
`LRESULT ret = (*pFunc)(params{msg, wp, lp}); // call user lambda`

Microsoft (R) C/C++ Optimizing Compiler Version `19.11.25547` for x64
`-sdl -guard:cf  -Zc:inline -Zc:rvalueCast -Zc:referenceBinding -Zc:strictStrings -std:c++latest`

**Comment by BeErikk** [comment]
Update:
The error was caused by the `-Zc:referenceBinding` compiler switch. Removing it solved the issue. The code still gives the warning:
`warning C4239: nonstandard extension used: 'argument': conversion from 'wl::params' to 'wl::params &'`

see [/Zc:referenceBinding (Enforce reference binding rules)](https://docs.microsoft.com/en-gb/cpp/build/reference/zc-referencebinding-enforce-reference-binding-rules)

**Comment by rodrigocfd** [comment]
Hi Erik, check if [this commit](https://github.com/rodrigocfd/winlamb/commit/f805ac2f791946b774db35be12ec0127b96b54b5) fixes these warnings. If not, please reopen the issue.

**Comment by BeErikk** [comment]
That did the trick! Thanks
