### ISSUE TITLE
error C3861: '_endthreadex': identifier not found 

### ISSUE THREAD

**Issue by sgf** [rodrigocfd/winlamb#3]
I Has been set RunTime Library to MultiThreads DLL (/MD) 
but always got this msg:
> error C3861: '_endthreadex': identifier not found 	WindowsProject1	c:\users\soar\source\repos\cpp\3dr\winlamb\internals\w_thread_capable.h	56	

Platform:windows10 x64 1803

**Comment by rodrigocfd** [comment]
@sgf, can you compile and run [this project](https://github.com/rodrigocfd/chromium-peeker), just like it is?

**Comment by sgf** [comment]
@rodrigocfd yes i can do that(compiled success).
but i dont know why my test project is wrong.
now i upload it.
[WindowsProject1.zip](https://github.com/rodrigocfd/winlamb/files/2161404/WindowsProject1.zip)

**Comment by rodrigocfd** [comment]
@sgf, your source code seems to be 100% correct, but did you use the Visual Studio wizard to generate the project? There's boilerplate code in your project, even some header files that have no use.

Try to create an empty project, just like [explained here](https://www.codeproject.com/Articles/1184175/WinLamb-using-Cplusplus-lambdas-to-handle-Win-mess#section2.3), and see if it works.

**Comment by sgf** [comment]
thank you.
