### ISSUE TITLE
process.h file name conflict

### ISSUE THREAD

**Issue by BeErikk** [rodrigocfd/winlamb#4]
Hi Rodrigo

I get 
`atlbase.h(5107): error C3861: '_beginthreadex': identifier not found`

which I believe is due to there's a winlamb file called **process.h** which hides the C library header with the same name containing the _beginthreadex function. Please rename the file.

FYI, I renamed mine to child_process.h to get further

**Comment by rodrigocfd** [comment]
@BeErikk After you renamed the file, did it work?

**Comment by BeErikk** [comment]
Yes
The Visual Studio project files are included first, then the system includes. I usually have a properties file with all paths specified, as the project files tend to have short lives. I also tend to have the project files separated from the source. Which means I usually end up with a bunch of local include paths and the concept of _current dir_ may be ambiguous and confusing. \#include "header" vs \#include <header> isn't always safe.

**Comment by rodrigocfd** [comment]
[Done](https://github.com/rodrigocfd/winlamb/commit/822fc71d73aac8301523f4eb8ec2f7e7b57b9897).
