### ISSUE TITLE
any plan use  thunk replace SetWindowsLong to support this pointer in WDNPROC call back?

### ISSUE THREAD

**Issue by sgf** [rodrigocfd/winlamb#7]
any plan use  thunk replace SetWindowsLong to support this pointer in WDNPROC call back?
an Example like https://github.com/shuangshu/TinyUI/blob/master/TinyFramework/Common/TinyThunk.h

**Comment by rodrigocfd** [comment]
You shouldn't need to deal with WNDPROC callback directly, because you can handle all the messages through lambda callbacks... what are the advantages of such an implementation?

**Comment by sgf** [comment]
@rodrigocfd maybe for this  https://stackoverflow.com/a/118412 ?

> While using the SetWindowLongPtr and GetWindowLongPtr to access the GWL_USERDATA might sound like a good idea, I would strongly recommend not using this approach.
> 
> This is the exactly the approached used by the Zeus editor and in recent years it has caused nothing but pain.
> 
> I think what happens is third party windows messages are sent to Zeus that also have their GWL_USERDATA value set. One application in particular was a Microsoft tool that provied an alternative way to enter Asian characters in any windows application (i.e. some sort of software keyboard utility).
> 
> The problem is Zeus always assumes the GWL_USERDATA data was set by it and tries to use the data as a this pointer, which then results in a crash.
> 
> If I was to do it all again with, what I know now, I would go for a cached hash lookup approach where the window handle is used as the key.

**Comment by rodrigocfd** [comment]
I've read that discussion in the past, and I considered other ways to store the `this` pointer. But notice the comment:

> Window messages do not have GWL_USERDATA. Windows have. Don't peek at messages for other windows, and expect to get the this pointer for your window.

He's correct. If a Microsoft utility did this in the past, the utility was totally wrong. Plus, using GWL_USERDATA is [what Raymond Chen does](https://blogs.msdn.microsoft.com/oldnewthing/20140203-00/?p=1893), and I specifically wrote about this approach in the end of [section 3.1 of the article](https://www.codeproject.com/Articles/1184175/WinLamb-using-Cplusplus-lambdas-to-handle-Win-mess#section3.1).

I don't really see a good reason to use such an obscure implementation, and I've never seen such a thing in any source I've read. GWL_USERDATA is the standard way... _a lot_ of programs will break if messing with GWL_USERDATA becomes the norm.

**Comment by sgf** [comment]
@rodrigocfd thank u, In fact, my understanding of this technique is more superficial.
just think of the thunk seems very efficient. because ATL and WTL use it.

**Comment by rodrigocfd** [comment]
@sgf I will surely take a look in ATL/WTL implementation, thanks for the insight.
